### ISSUE TITLE
Cannot find module 'btcpay-greenfield-node-client/dist/core/OpenAPI'

### ISSUE THREAD

**Issue by bas24** [AryanJ-NYC/btcpay-greenfield-node-client#1]
Trying to use in my node project your module and getting Cannot find module 'btcpay-greenfield-node-client/dist/core/OpenAPI' message on application run
Installed with npm, everything according your README, folder exist in node_modules
node version 14.8.0
npm version 6.14.7

**Comment by AryanJ-NYC** [comment]
Can you give me some sample code that you're using that's breaking?

**Comment by bas24** [comment]
Sure:
```javascript
import { OpenAPI } from 'btcpay-greenfield-node-client';
import {
  BTCPAY_SERVER_URL,
  BTCPAY_API_KEY,
  BTCPAY_ROOT_USERNAME,
  BTCPAY_ROOT_PASSWORD,
} from '../env';

OpenAPI.BASE = BTCPAY_SERVER_URL;
OpenAPI.TOKEN = BTCPAY_API_KEY;
OpenAPI.USERNAME = BTCPAY_ROOT_USERNAME;
OpenAPI.PASSWORD = BTCPAY_ROOT_PASSWORD;

module.exports = { OpenAPI };
```

**Comment by bas24** [comment]
Found what is wrong - my side with IDE. Thank you for support

**Comment by AryanJ-NYC** [comment]
Awesome. Let me know if there's anything else I can help with!
